#!/bin/bash

# Change to the project directory
cd ~/taskify-backend

# Pull the latest changes from GitHub
git pull origin main

# Stop the PM2 process
pm2 stop taskify-backend

# Build the application
npm run build

# Start the application with PM2
pm2 restart taskify-backend --update-env

# Log the deployment
echo "Deployment completed at $(date)" >> ~/deployment.log